name: Release Process

on:
  # Events
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Jobs
  generate-release:
    name: Create GitHub Release
    # Runner OS
    runs-on: ubuntu-latest
    steps:
    - name: Print the input tag to STDOUT
      run: echo "I am inside the workflow"