name: Release Process

on:
  # Events
  push:
    branches:
      - main
    # paths:
    #   - user_experience/infra/**
  #workflow_dispatch:

jobs:
  terraform:
    name: "Terraform Infrastructure Change Management"
    runs-on: ubuntu-latest
    environment: development
    env:
      VARS_JSON: ${{ toJSON(vars) }}
    defaults:
      run:
        shell: bash
        # We keep Terraform files in the terraform directory.
        working-directory: ./user_experience/infra

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v3

      - name: Generate .env file
        run: |
          echo "$VARS_JSON" | jq -r 'keys[] as $k | "\($k)=\(.[$k])"' >> .env;
          cat .env;

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.2

      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform format
        id: fmt
        run: terraform fmt -check

      - name: Terraform validate
        id: validate
        run: terraform validate